  - name: Add the InfluxDB executables to the PATH
    become: yes
    command: |
      cd /tmp
      wget https://dl.influxdata.com/influxdb/releases/influxdb2-2.4.0-linux-amd64.tar.gz
      tar -xzvf influxdb2-2.4.0-linux-amd64.tar.gz
      sudo cp influxdb2-2.4.0-linux-amd64/influxdb /usr/local/bin/
